<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeFrameworkVersion>10.0.12</RuntimeFrameworkVersion>
    <RollForward>Disable</RollForward>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GraphQL" Version="8.8.5" />
    <PackageReference Include="GraphQL.SystemTextJson" Version="8.8.5" />
    <PackageReference Include="Platform.Data.Doublets" Version="0.18.1" />
    <Content Include="../schema/links.graphql" Link="links.graphql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
