image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore
      dotnet build
  - name: Launch Deep
    before: cd dev; npm ci; npm run git-shh-to-https; npm run packages
    init: npm ci; npm run git-shh-to-https; npm run gitpod; npm run rm-migrates; npm ci && npm run clear;
    command: npm run gitpod-start; npm ci && npm run clear;

vscode:
  extensions:
    - muhammad-sammy.csharp
    - ms-azuretools.vscode-docker
    - graphql.vscode-graphql
    - yzhang.markdown-all-in-one
    - ms-vscode.vscode-typescript-tslint-plugin
    - hediet.vscode-drawio
    - ms-azuretools.vscode-docker

ports:
  - port: 3007
    onOpen: open-browser
    visibility: public
  - port: 4000
    onOpen: open-browser
    visibility: public
  - port: 3006
    onOpen: ignore
    visibility: public
  - port: 8080
    onOpen: ignore
    visibility: public
